export const FIELD_NAMES = [
  ["tenure"],
  [
    "home_description",
    "comm_standing",
    "rent",
    "amortization",
    "residence",
    "educ_attain",
    "birth_place",
    "birth_day",
    "status",
    "email",
    "contact_num",
    "gender",
    "last_name",
    "first_name",
  ],
  [
    "bills",
    "insurance",
    "transportation",
    "education_exp",
    "rental_exp",
    "living_exp",
    "business",
    "salary",
    "rate",
    "income",
  ],
  [
    "mother_last",
    "mother_middle",
    "mother_first",
    "father_last",
    "father_middle",
    "father_first",
  ],
  [],
];

export const ADDRESS_NAMES = [
  [],
  [
    "prev_lot_num",
    "prev_purok",
    "prev_brgy",
    "prev_city",
    "prev_province",
    "prev_region",
    "lot_num",
    "purok",
    "brgy",
    "city",
    "province",
    "region",
  ],
  [],
  [
    "p_prev_lot_num",
    "p_prev_purok",
    "p_prev_brgy",
    "p_prev_city",
    "p_prev_province",
    "p_prev_region",
    "p_lot_num",
    "p_purok",
    "p_brgy",
    "p_city",
    "p_province",
    "p_region",
  ],
  [],
];

export const FORM_LABELS = {
  personal_info: {
    civil_stat: "Marital Status",
    birthDate: "Date of Birth",
    birth_place: "Place of Birth",
    getEducAttain: "Educational Attainment",
    getResidence: "Residential Status",
    getAmortization: "Amortization Monthly",
    getRent: "Rent Monthly",
    sss: "SSS/GSIS #",
    tin: "TIN #",
  },
  employment_info: {
    A: {
      getIncome: "Source of Income",
      superior: "Immediate Superior",
      employment_status: "Employment Status",
      yrs_in_service: "Years in Service",
      getRate: "Monthly/Daily Rate",
      employer: "Employer",
      employer_address: "Employer Address",
    },
    B: {
      getSalary: "Salary",
      business: "Business",
    },
    C: {
      getLivingExp: "Living",
      getRentalExp: "Rental",
      getEducationExp: "Education",
      getTransportation: "Transportation",
      getInsurance: "Insurance",
      getBills: "Electric/Water Bill",
    },
  },
  family_info: {
    spouse_name: "Spouse Name",
    birthDate: "Date of Birth",
    spouse_work: "Spouse Working?",
    children_num: "Number of Children",
    children_dep: "Dep. Children",
    school: "Schooling Children",
  },
  address: {
    personal_pres: "Present Address",
    personal_prev: "Previous Address",
    parent_pres: "Parent's Present Address",
    parent_prev: "Parent's Previous Address",
    spouse_pres: "Spouse's Present Address",
    spouse_prev: "Spouse's Previous Address",
    comaker_pres: "Present Address",
    comaker_perm: "Permanent Address",
    sp_parent_pres: "Parent's Present Address",
    sp_parent_prev: "Parent's Previous Address"
  },
  other: {
    comm_standing: "Community Standing",
    home_description: "Home Description",
    father_first: "First name",
    father_middle: "Middle name",
    father_last: "Last name",
    mother_first: "First name",
    mother_middle: "Middle name",
    mother_last: "Last name",
    sp_father_first: "Firsth Name",
    sp_father_middle: "Middle Name",
    sp_father_last: "Last Name",
    sp_mother_first: "First Name",
    sp_mother_middle: "Middle Name",
    sp_mother_last: "Last Name",
  },
  comaker: {
    facebook: "Facebook",
    birth_day: "Birth Day",
    birth_place: "Birth Place",
    religion: "Religion",
    tribe: "Tribe",
    educ_attain: "Educational Attainment",
    citizenship: "Citizenship",
    occupation: "Occupation",
    yrs_in_service: "Years in Service",
    employment_status: "Employment Status",
    employer: "Employer",
  },
  comaker_spouse: {
    spouse_first: "First Name",
    spouse_middle: "Middle Name",
    spouse_last: "Last Name",
    sp_citizenship: "Citizenship",
    sp_occupation: "Occupation",
    sp_yrs_in_service: "Years in Service",
    sp_emp_status: "Employment Status",
    sp_employer: "Employer",
  },
};

export const REPORT_LABELS = {
  first_unit: "First Unit Applied",
  delivered: "Delivered?",
  remarks: "Other Remarks",
  outlet: "Outlet",
};
