export const SPECS = {
  engine: "Engine",
  compression: "Compression Ratio",
  displacement: "Displacement (cc)",
  horsepower: "Horsepower (hp)",
  torque: "Torque (Nm)",
  fuel: "Fuel System",
  drive: "Final Drive",
  transmission: "Transmission",
  cooling: "Cooling System",
  front_suspension: "Front Suspension",
  rear_suspension: "Rear Suspension",
  frame: "Frame Type",
  travel: "Front/Rear Travel (mm/in)",
  swingarm: "Swingarm Type",
  dry_weight: "Dry Weight",
  wet_weight: "Wet Weight",
  seat: "Seat Height (mm/in)",
  wheelbase: "Wheelbase",
  fuel_tank: "Fuel Tank Capacity",
  clearance: "Ground Clearance",
  tires: "Tire Size",
  wheel: "Wheel Type",
  brakes: "Brakes",
  abs: "ABS",
  traction: "Traction Control",
  tft: "TFT Display",
  lighting: "Lighting",
  ride_mode: "Riding Modes",
  quickshift: "Quickshifter",
  cruise: "Cruise Control",
};
